# This is a basic workflow to help you get started with Actions

name: Installation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:

  build-and-test:
    name: Install and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyrossgeo
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pyross
        shell: bash -l {0}
        run: |
          conda activate pyrossgeo
          make
      #     make test
      # - name: test-pyross
      #   shell: bash -l {0}
      #   run: |
      #     make test
    

                # make nbtest
