name: Notebooks

on:

jobs:

  build-and-test:
    name: notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyrossgeo
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pyross-geo
        shell: bash -l {0}
        run: |
          conda activate pyrossgeo
          make
      #    make nbtest path=examples_mft/
